server:
  port: 7002

spring:
  servlet:
    multipart:
      max-file-size: 100GB
      max-request-size: 100GB
  mail:
    host: smtp.gmail.com
    port: 587
    username: [your_mail]
    password: [your_mail_password]
    protocol: smtp
    tls: true
    from: [your_mail]
    properties.mail.smtp:
      auth: true
      starttls.enable: true
      ssl.trust: smtp.gmail.com

mail:
  shutdown-after-load: false
  is-test-env: true
  security:
    cors:
      allowed-hosts:
        - /**